### PR TITLE
Stat proc improvement

### PR DESCRIPTION
**Pull request by dcesari**
Addresses #8, uniforms the statistical processing for sparse/gridded, analysis/forecast, vertime/reftime data, filling the gaps and adding some new features. Results are not expected to change but we never know.

### CODE REVIEW

**Comment by pat1** [comment]
L'uso di questo branch su rmap ha comportato qualche problema come mostra questo grafico di temperatura:
http://rmapv.rmap.cc/graphite/S/6

**Comment by dcesari** [comment]
Si riesce ad isolare input (e opzionalmente output)? Immagino venga calcolata una media trascinata dei campionamenti per creare una misura istantanea?!

**Comment by pat1** [comment]
I dati di partenza si possono ottenere da qui:
http://rmapv.rmap.cc/borinud/api/v1/jsonline/dancast78/1137634,4449217/rmap/254,0,0/103,2000,-,-/B12101/timeseries/2017/08/23?dsn=sample_fixed

La sequenza delle elaborazioni è una cosa tipo questa:

'v7d_transform' '--input-format' 'dba' '--output-format' 'dba' '--variable-list' 'B12101' '--level' '103,2000,,' '--timerange' '254,0,0' '--start-date' '2017-08-18 09:00:00' '--end-date' '2017-08-24 09:00:00' '--comp-start' '2017-08-18 09:00:00' '--comp-step' '0000000000 00:01:00.000' '--comp-frac-valid' '.0002' '--comp-stat-proc' '254:0' 'mysql:///sample_fixed?user=rmap&password=rmap' 'mysql:///sample_fixed?user=rmap&password=password'
'v7d_transform' '--input-format' 'dba' '--output-format' 'BUFR' '--variable-list' 'B12101' '--level' '103,2000,,' '--timerange' '0,0,60' '--start-date' '2017-08-18 09:00:00' '--end-date' '2017-08-24 09:00:00' '--comp-start' '2017-08-18 09:00:00' '--comp-step' '0000000000 00:15:00.000' '--comp-frac-valid' '.9' '--comp-stat-proc' '0:0' 'mysql:///sample_fixed?user=rmap&password=password' '-'
'v7d_transform' '--input-format' 'dba' '--output-format' 'BUFR' '--variable-list' 'B12101' '--level' '103,2000,,' '--timerange' '0,0,60' '--start-date' '2017-08-18 09:00:00' '--end-date' '2017-08-24 09:00:00' '--comp-start' '2017-08-18 09:00:00' '--comp-step' '0000000000 00:15:00.000' '--comp-frac-valid' '.9' '--comp-stat-proc' '0:2' 'mysql:///sample_fixed?user=rmap&password=password' '-'
'v7d_transform' '--input-format' 'dba' '--output-format' 'BUFR' '--variable-list' 'B12101' '--level' '103,2000,,' '--timerange' '0,0,60' '--start-date' '2017-08-18 09:00:00' '--end-date' '2017-08-24 09:00:00' '--comp-start' '2017-08-18 09:00:00' '--comp-step' '0000000000 00:15:00.000' '--comp-frac-valid' '.9' '--comp-stat-proc' '0:3' 'mysql:///sample_fixed?user=rmap&password=password' '-'
'v7d_transform' '--input-format' 'dba' '--output-format' 'BUFR' '--variable-list' 'B12101' '--level' '103,2000,,' '--timerange' '0,0,60' '--start-date' '2017-08-18 09:00:00' '--end-date' '2017-08-24 09:00:00' '--comp-start' '2017-08-18 09:00:00' '--comp-step' '0000000000 00:01:00.000' '--comp-frac-valid' '.9' '--comp-stat-proc' '0:254' 'mysql:///sample_fixed?user=rmap&password=password' '-'
'v7d_transform' '--input-format' 'BUFR' '--output-format' 'BUFR' '--comp-start' '2017-08-18 09:00:00' '--comp-step' '0000000000 00:15:00.000' '--comp-fill-data' '--comp-fill-tolerance' '0000000000 00:00:60.000' '--comp-filter-time' '-' '-'
'dbadb' 'export' '--dsn' 'mysql:///sample_mobile?user=rmap&password=rmap' 'varlist' 'B12101' 'yearmin' '2017' 'monthmin' '8' 'daymin' '18' 'hourmin' '9' 'minumin' '0' 'secmin' '0' 'yearmax' '2017' 'monthmax' '8' 'daymax' '24' 'hourmax' '9' 'minumax' '0' 'secmax' '0'
'dbadb' 'import' '--dsn' 'mysql:///report_mobile?user=rmap&password=rmap'

**Comment by dcesari** [comment]
There was a serious error in the weighted case and a minor difference in the computation of the end of computation interval, now the results are the same and apparently correct.

**Pull request merged**
